source 'https://github.com/CocoaPods/Specs.git'

target 'baseapp-ios-core-v1_Example' do
  platform :ios, '10.0'
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'baseapp-ios-core-v1', :path => '../'
#  pod 'baseapp-ios-core-v1/ARKit', :path => '../'
  pod 'baseapp-ios-core-v1/FilePreviewer', :path => '../'
  pod 'SwiftLint'

  target 'baseapp-ios-core-v1_Tests' do
    inherit! :search_paths
  end

end

target 'Example' do
  platform :watchos, '3.0'
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'baseapp-ios-core-v1', :path => '../'
end

target 'Example Extension' do
  platform :watchos, '3.0'
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'baseapp-ios-core-v1', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
